class Mecanico{
    constructor(
        IDMecanico,
		NombreMecanico,
		ApePatMecanico,
        ApeMatMecanico,
        CorreoMecanico,
        TelefonoMecanico,
        Area
    ){
        this.IDMecanico,
		this.NombreMecanico,
		this.ApePatMecanico,
        this.ApeMatMecanico,
        this.CorreoMecanico,
        this.TelefonoMecanico
        this.Area
    }
}
module.exports=Mecanico;